In [1]:
import torch

In [2]:
torch.rand(3,4)

tensor([[0.1518, 0.3928, 0.6438, 0.8670],
        [0.8835, 0.3239, 0.7571, 0.8829],
        [0.1617, 0.9310, 0.2267, 0.7569]])

In [3]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
torch.arange(10,20).reshape(2,5)

tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [5]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x ** 2
y.backward(torch.tensor([1.0, 1.0]))
print(x.grad)


tensor([4., 6.])


y = x ** 2 means: y[0] = 2^2 = 4, y[1] = 3^2 = 9.

y.backward(...) computes the gradient of y w.r.t. x using chain rule:

dy/dx = 2x → at x = [2.0, 3.0], the gradient = [4.0, 6.0]

In [6]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 3
y.backward(torch.tensor([1.0, 1.0, 1.0]))
print("Gradient of y = x^3 is:", x.grad)  # Should print 3*x^2


Gradient of y = x^3 is: tensor([ 3., 12., 27.])


In [7]:
v = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
z = v * 2
z.backward(torch.tensor([1.0, 1.0, 1.0]))  # Simulate sum(z)
print(v.grad)  # tensor([2., 2., 2.])


tensor([2., 2., 2.])


In [8]:
import tensorflow as tf
tf.random.uniform((2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7452525 , 0.00569022],
       [0.079409  , 0.7438755 ]], dtype=float32)>

In [9]:
torch.randn(2,2)

tensor([[-1.0535, -0.8992],
        [ 0.1945,  1.0450]])

In [10]:
x = torch.tensor(3.0, requires_grad=True)

for i in range(3):
    y = x * i
    y.backward()
    print(x.grad)  # Gradients accumulate!

    x.grad.zero_()  # Clear old gradients before next loop



tensor(0.)
tensor(1.)
tensor(2.)


In [11]:
x = torch.tensor(5.0, requires_grad=True)
y = (x + 2) ** 3
y.backward()
print(f"x: {x.item()}, dy/dx: {x.grad.item()}")


x: 5.0, dy/dx: 147.0


y=wx+b and z=sigmoid(y) we need to find gradient of x and b

In [21]:
x=torch.tensor([2.,3.])
w=torch.tensor([1.0, 1.0],requires_grad=True)
b=torch.tensor([4.],requires_grad=True)
y_true=torch.tensor([6])

z=torch.matmul(w,x)+b

y_pred=torch.sigmoid(z)

loss = - (y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
loss.backward()

In [22]:
w.grad

tensor([-10.0002, -15.0004])

visualizing the flow

In [ ]:
from torchviz import make_dot

# Create the tensor and perform operations as before
# Create the tensor and perform operations as before
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = y + 2

# Visualize the computation graph
make_dot(z, params={"x": x}).render("graph", format="png")


'graph.png'