In [472]:
import torch
import numpy

In [473]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [474]:
X = X[y != 2] # Filter out class 2 (Iris-virginica) for binary classification

y = y[y != 2]

In [475]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [476]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [477]:
X[:10]

array([[-0.5810659 ,  0.84183714, -1.01297765, -1.04211089],
       [-0.89430898, -0.2078351 , -1.01297765, -1.04211089],
       [-1.20755205,  0.21203379, -1.08231219, -1.04211089],
       [-1.36417359,  0.00209934, -0.94364311, -1.04211089],
       [-0.73768744,  1.05177159, -1.01297765, -1.04211089],
       [-0.11120129,  1.68157493, -0.80497402, -0.68644165],
       [-1.36417359,  0.63190269, -1.01297765, -0.86427627],
       [-0.73768744,  0.63190269, -0.94364311, -1.04211089],
       [-1.67741667, -0.41776955, -1.01297765, -1.04211089],
       [-0.89430898,  0.00209934, -0.94364311, -1.21994552]])

In [478]:
X=torch.from_numpy(X)
y=torch.from_numpy(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [479]:
X.dtype

torch.float64

In [480]:
X_train.shape

torch.Size([70, 4])

In [481]:
class My_SimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True) #  1 neuron
        self.bias=torch.ones(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias #calculate bias
        y_pred=torch.sigmoid(z) #predicting
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss


In [482]:
model=My_SimpleNN(X_train)
model.weights[:5]

tensor([[0.6336],
        [0.5423],
        [0.6679],
        [0.7797]], dtype=torch.float64, grad_fn=<SliceBackward0>)

In [483]:
epochs=30
lr=.01 
for epoch in range(epochs):
    y_pred=model.forward(X_train)

    loss=model.loss_function(y_pred,y_train)
    print(f"Epoch: {epoch+1} Loss: {loss.item()}")
    loss.backward()

    with torch.no_grad():
        model.weights-=lr*model.weights.grad
        model.bias-=lr*model.bias.grad
    
    model.weights.grad.zero_()
    model.bias.grad.zero_()


Epoch: 1 Loss: 1.0727771474598757
Epoch: 2 Loss: 1.0704679762726639
Epoch: 3 Loss: 1.0681716376766435
Epoch: 4 Loss: 1.0658880840334002
Epoch: 5 Loss: 1.063617267617007
Epoch: 6 Loss: 1.061359140618401
Epoch: 7 Loss: 1.059113655149694
Epoch: 8 Loss: 1.056880763248408
Epoch: 9 Loss: 1.0546604168816502
Epoch: 10 Loss: 1.0524525679502172
Epoch: 11 Loss: 1.0502571682926307
Epoch: 12 Loss: 1.0480741696891103
Epoch: 13 Loss: 1.0459035238654764
Epoch: 14 Loss: 1.0437451824969886
Epoch: 15 Loss: 1.041599097212122
Epoch: 16 Loss: 1.039465219596274
Epoch: 17 Loss: 1.0373435011954097
Epoch: 18 Loss: 1.0352338935196437
Epoch: 19 Loss: 1.0331363480467592
Epoch: 20 Loss: 1.031050816225663
Epoch: 21 Loss: 1.028977249479782
Epoch: 22 Loss: 1.0269155992103947
Epoch: 23 Loss: 1.0248658167999045
Epoch: 24 Loss: 1.0228278536150561
Epoch: 25 Loss: 1.0208016610100852
Epoch: 26 Loss: 1.0187871903298167
Epoch: 27 Loss: 1.0167843929127034
Epoch: 28 Loss: 1.0147932200938052
Epoch: 29 Loss: 1.0128136232077152
Ep

In [484]:
with torch.no_grad():
    y_pred=model.forward(X_test)
    y_pred=(y_pred>.5).float()
    accuracy=(y_pred==y_test).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.48222222924232483


In [485]:
import torch
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Filter out class 2 (Iris-virginica) for binary classification
X = X[y != 2]
y = y[y != 2]

# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split into 70% training and 30% test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Convert to PyTorch tensors with float32 type for memory efficiency
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)  # Reshape to column vector
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)  # Reshape to column vector

# Define the manual simple neural network as per the user's code
class My_SimpleNN:
    def __init__(self):
        self.weights = torch.rand(X_train.shape[1], 1, dtype=torch.float32, requires_grad=True)
        self.bias = torch.ones(1, dtype=torch.float32, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias  # Linear combination
        y_pred = torch.sigmoid(z)  # Sigmoid activation
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        # Binary cross-entropy loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

# Initialize the model
model = My_SimpleNN()

# Training settings
epochs = 30
lr = 0.01

# Training loop
for epoch in range(epochs):
    y_pred = model.forward(X_train)
    loss = model.loss_function(y_pred, y_train)
    print(f"Epoch: {epoch+1} Loss: {loss.item()}")
    
    loss.backward()  # Backpropagation
    
    # Gradient update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad
    
    model.weights.grad.zero_()  # Zero gradients
    model.bias.grad.zero_()  # Zero gradients

# Testing the model
with torch.no_grad():
    y_pred = model.forward(X_test)
    y_pred = (y_pred > 0.5).float()  # Thresholding at 0.5
    accuracy = (y_pred == y_test).float().mean()
    accuracy_percentage = accuracy.item() * 100

accuracy_percentage


Epoch: 1 Loss: 0.2509191930294037
Epoch: 2 Loss: 0.2498241364955902
Epoch: 3 Loss: 0.24873700737953186
Epoch: 4 Loss: 0.24765761196613312
Epoch: 5 Loss: 0.2465859204530716
Epoch: 6 Loss: 0.2455219328403473
Epoch: 7 Loss: 0.24446547031402588
Epoch: 8 Loss: 0.24341654777526855
Epoch: 9 Loss: 0.24237507581710815
Epoch: 10 Loss: 0.24134096503257751
Epoch: 11 Loss: 0.24031418561935425
Epoch: 12 Loss: 0.2392946481704712
Epoch: 13 Loss: 0.23828233778476715
Epoch: 14 Loss: 0.23727713525295258
Epoch: 15 Loss: 0.23627899587154388
Epoch: 16 Loss: 0.2352878600358963
Epoch: 17 Loss: 0.23430369794368744
Epoch: 18 Loss: 0.23332639038562775
Epoch: 19 Loss: 0.23235584795475006
Epoch: 20 Loss: 0.23139217495918274
Epoch: 21 Loss: 0.23043517768383026
Epoch: 22 Loss: 0.22948478162288666
Epoch: 23 Loss: 0.22854101657867432
Epoch: 24 Loss: 0.22760380804538727
Epoch: 25 Loss: 0.22667300701141357
Epoch: 26 Loss: 0.2257487028837204
Epoch: 27 Loss: 0.22483070194721222
Epoch: 28 Loss: 0.223919078707695
Epoch: 29 

89.99999761581421